/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false`
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "TeamAgent";
	}
	interface Env {
		AI: Ai;
		TeamAgent: DurableObjectNamespace<import("./src/server").TeamAgent>;
	}
}
interface Env extends Cloudflare.Env {}
